
spring.datasource.url=jdbc:postgresql://localhost:5432/multi_tent_db
spring.datasource.username=user_secret
spring.datasource.password=password_secret
jwt.secret=mysupersecuresecretkeythatcontainsatleast32characters
jwt.expiration=86400000