spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false
logging.level.com.tupackage=WARN
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

